spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fundloader_db?useSSL=false
    username: root
    password: 1234
  jpa:
    properties:
      hibernate:
        ddl-auto: update
  sql:
    init:
      mode: always