spring:
  datasource:
    url: jdbc:mysql://mysqldb:3306/fundloader_db?useSSL=false
    username: root
    password: 123456
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        ddl-auto: update
  sql:
    init:
      mode: always